title: Creative Homes - Gold Coast Builder
email: hello@creativehomes.com.au
description: Creative Homes is a family operated construction company on the Gold Coast. Our buildings reflect the Australian lifestyle that combine the best of indoor and outdoor living.
baseurl:  # the subpath of your site, e.g. /blog
url: "https://creativehomes.com.au" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
assets: /assets/images/projects
# Build settings
plugins:
  - jekyll-feed
  - jekyll-purgecss
  - jekyll-sitemap
  
css_dir: "spaz/assets/css/" 
# defaults to "css"

# Permalinks
permalink: pretty

include:
  - _pages
  - _redirects

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - pages
  - gulpfile.babel.js
  - package.json
  - _sass
  - js
  - .sass-cache
  - vendor
  - .cache

  # jekyll-webp settings

webp:
  enabled: true

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true

  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets/images"]

  # Whether to search in nested directories or not
  nested: false

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: true

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
